---
- name: create system group
  group:
    name: "{{ victoriametrics_system_group }}"
    system: true
    state: present
  when: victoriametrics_system_group != "root"
  become: true
  tags: victoriametrics

- name: create system user
  user:
    name: "{{ victoriametrics_system_user }}"
    system: true
    shell: "/sbin/nologin"
    group: "{{ victoriametrics_system_group }}"
    createhome: false
  when: victoriametrics_system_user != "root"
  become: true
  tags: victoriametrics

- name: create data directory
  file:
    path: "{{ victoriametrics_data_dir }}"
    state: directory
    owner: "{{ victoriametrics_system_user }}"
    group: "{{ victoriametrics_system_group }}"
    mode: "0755"
  become: true
  tags: victoriametrics

- name: check if victoriametrics is installed
  stat:
    path: "/usr/local/bin/victoriametrics"
  register: __victoriametrics_is_installed
  become: true
  tags: victoriametrics

- name: gather currently installed victoriametrics version (if any)
  command: "/usr/local/bin/victoriametrics -version"
  args:
    warn: false
  changed_when: false
  register: __victoriametrics_current_version_output
  when: __victoriametrics_is_installed.stat.exists
  become: true
  tags: victoriametrics

- block:
  - name: get latest release
    uri:
      url: "https://api.github.com/repos/VictoriaMetrics/VictoriaMetrics/releases/latest"
      method: GET
      return_content: true
      status_code: 200
      body_format: json
      validate_certs: false
      user: "{{ lookup('env', 'GH_USER') | default(omit) }}"
      password: "{{ lookup('env', 'GH_TOKEN') | default(omit) }}"
    environment: "{{ proxy_env }}"
    no_log: "{{ not lookup('env', 'MOLECULE_DEBUG') | bool }}"
    register: _latest_release
    until: _latest_release.status == 200
    tags: victoriametrics
    retries: 5

  - name: "set victoriametrics version to {{ _latest_release.json.tag_name[1:] }}"
    set_fact:
      victoriametrics_version: "{{ _latest_release.json.tag_name[1:] }}"
    tags: victoriametrics
  when: victoriametrics_version == "latest"
  delegate_to: localhost
  run_once: true
  become: true
  tags: victoriametrics

- block:
  - name: get checksum list from github
    set_fact:
      _checksums: "{{ lookup('url', 'https://github.com/VictoriaMetrics/VictoriaMetrics/releases/download/v' + victoriametrics_version + '/victoria-metrics-' + go_arch + '-v' + victoriametrics_version + '_checksums.txt', wantlist=True) | list }}"
    environment: "{{ proxy_env }}"
    run_once: true
    become: true
    tags: victoriametrics

  - name: "get checksum for {{ go_arch }} architecture"
    set_fact:
      victoriametrics_checksum: "{{ item.split(' ')[0] }}"
    with_items: "{{ _checksums }}"
    when: "('linux-' + go_arch + '.tar.gz') in item"
    become: true
    tags: victoriametrics

  - name: download binary to local folder
    get_url:
      url: "https://github.com/VictoriaMetrics/VictoriaMetrics/releases/download/v{{ victoriametrics_version }}/victoria-metrics-{{ go_arch }}-v{{ victoriametrics_version }}.tar.gz"
      dest: "/tmp/victoriametrics-{{ victoriametrics_version }}.linux-{{ go_arch }}.tar.gz"
      checksum: "sha256:{{ victoriametrics_checksum }}"
    environment: "{{ proxy_env }}"
    register: _download_binary
    until: _download_binary is succeeded
    retries: 5
    delay: 2
    delegate_to: localhost
    check_mode: false
    become: true
    tags: victoriametrics

  - name: unpack binary
    unarchive:
      src: "/tmp/victoriametrics-{{ victoriametrics_version }}.linux-{{ go_arch }}.tar.gz"
      dest: "/tmp"
      creates: "/tmp/victoriametrics-{{ victoriametrics_version }}.linux-{{ go_arch }}/victoriametrics"
    delegate_to: localhost
    check_mode: false
    become: true
    tags: victoriametrics

  - name: propagate binaries
    copy:
      src: "/tmp/victoriametrics-{{ victoriametrics_version }}.linux-{{ go_arch }}/victoria-metrics-prod"
      dest: "{{ victoriametrics_binary_install_dir }}/victoriametrics"
      mode: 0755
      owner: root
      group: root
    notify: restart victoriametrics
    when: not ansible_check_mode
    become: true
    tags: victoriametrics
  when: (not __victoriametrics_is_installed.stat.exists) or (__victoriametrics_current_version_output.stderr_lines[0].split(" ")[2] != victoriametrics_version)

- block:
  - name: create config directory
    file:
      path: "{{ victoriametrics_config_dir }}"
      state: directory
      owner: "{{ victoriametrics_system_user }}"
      group: "{{ victoriametrics_system_group }}"
      mode: 0755
    become: true
    tags: victoriametrics

  - name: create prometheus config file
    template:
      src: victoriametrics.config.json.j2
      dest: "{{ victoriametrics_config_dir }}/config.yml"
      owner: "{{ victoriametrics_system_user }}"
      group: "{{ victoriametrics_system_group }}"
      mode: 0644
    notify: restart victoriametrics
    become: true
    tags: victoriametrics
  when: victoriametrics_prometheus_config length > 0

- name: create systemd service unit
  template:
    src: victoriametrics.service.j2
    dest: /etc/systemd/system/victoriametrics.service
    owner: root
    group: root
    mode: 0644
  notify: restart victoriametrics
  become: true
  tags: victoriametrics

- name: enable capabilities to ports lower than port 1024
  capabilities:
    path: "{{ victoriametrics_binary_install_dir }}/victoriametrics"
    capability: CAP_NET_BIND_SERVICE+ep
    state: present
  when: victoriametrics_web_listen_port <= 1024
  tags: victoriametrics

- name: install selinux dependencies
  package:
    name: "{{ item }}"
    state: present
  environment: "{{ proxy_env }}"
  with_items: "{{ victoriametrics_selinux_packages }}"
  register: _install_packages
  until: _install_packages is succeeded
  retries: 5
  delay: 2
  when:
    - ansible_version.full is version_compare('2.4', '>=')
    - ansible_selinux.status == "enabled"
  become: true
  tags: victoriametrics

- name: allow binding to port in selinux
  seport:
    ports: "{{ victoriametrics_web_listen_port }}"
    proto: tcp
    setype: http_port_t
    state: present
  when:
    - ansible_version.full is version_compare('2.4', '>=')
    - ansible_selinux.status == "enabled"
  become: true
  tags: victoriametrics

- name: check whether ufw status is active
  command: "ufw status"
  changed_when: False
  ignore_errors: True
  register: _ufw_status
  become: true
  when:
    - victoriametrics_allow_firewall
    - ansible_os_family == 'Debian'
  tags: victoriametrics

- name: check whether firewalld status is active
  command: "firewall-cmd --state"
  changed_when: False
  ignore_errors: True
  register: _firewalld_status
  become: true
  when: ansible_os_family == 'RedHat'
  tags: victoriametrics

- name: configure ufw
  community.general.ufw:
    rule: allow
    port: "{{ victoriametrics_web_listen_port }}"
    proto: tcp
    state: enabled
    comment: "Node Exporter"
  changed_when: False
  ignore_errors: True
  notify: reload ufw
  become: true
  tags: victoriametrics
  when:
    - "'active' in _ufw_status.stdout"
    - ansible_os_family == 'Debian'
    - victoriametrics_allow_firewall

- name: configure firewalld
  firewalld:
    port: "{{ victoriametrics_web_listen_port }}/tcp"
    permanent: yes
    state: true
  changed_when: False
  ignore_errors: True
  when:
    - "'running' in _firewalld_status.stdout"
    - victoriametrics_allow_firewall
    - ansible_os_family == 'RedHat'
  notify: reload firewalld
  become: true
  tags: victoriametrics

- name: start and enable victoriametrics
  systemd:
    daemon_reload: true
    name: victoriametrics
    enabled: true
    state: started
  become: true
  tags: victoriametrics